### ISSUE TITLE
[Question] why is RGR | ARGR displayed on Android instead of RGB | ARGB?

### ISSUE THREAD

**Issue by felixkrautschuk** [bradmartin/nativescript-color-picker#10]
Hi, maybe this is a stupid question, but I just wonder why the picker displays RGR | ARGR alongside the sliders on Android when choosing the 'RGB' or 'ARGB' colorMode. What does the second 'R' mean?

**Comment by bradmartin** [comment]
There is an issue with the android library version this plugin uses 😄 - I think it was fixed in a more recent version of the native android library. I'll double check. Thanks for logging the issue though 👍
