### ISSUE TITLE
Error calling show

### ISSUE THREAD

**Issue by finger563** [bradmartin/nativescript-color-picker#11]
```
ERROR Error: Uncaught (in promise): TypeError: (intermediate value).initialColor(...).colorMode(...).indicatorMode(...).onColorSelected(...).create(...).show is not a function
JS: TypeError: (intermediate value).initialColor(...).colorMode(...).indicatorMode(...).onColorSelected(...).create(...).show is not a function
````

**Comment by finger563** [comment]
might be from newer version of `vintage-chroma`, which is now `1.5` as opposed to the `1.2` that the plugin was built on

**Comment by finger563** [comment]
changed back to `1.2` and it works now

**Comment by bradmartin** [comment]
I'd love to get the plugin updated with the new lib version. I don't have the time for it right now but if you're interested and want to contribute I can answer Q's to assist 😄 thanks
