### ISSUE TITLE
how to parse the int color?

### ISSUE THREAD

**Issue by peppeg85** [bradmartin/nativescript-color-picker#13]
hi, thanks for your colorpicke, but..how to retrieve the rgb components? the int result parsed with toString(16) isn't right, how could i get the three components? thank you

**Comment by peppeg85** [comment]
done, thank you:

        console.log('color int: ' + result);

        console.log('color r: ' + ((result >> 16) & 0xFF).toString(16));
        console.log('color g: ' + ((result >> 8) & 0xFF).toString(16));
        console.log('color b: ' + (result & 0xFF).toString(16));

**Comment by bradmartin** [comment]
Try using the `Color` class from the NS core modules: https://docs.nativescript.org/api-reference/classes/_color_.color - construct the color and then you can access the props. That's what I'd try first 👍

**Comment by peppeg85** [comment]
thanks bradmartin, i will try
